# Stage 1 - Build
FROM node:14 as build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage 2 - Serve
FROM php:7.4-apache as production-stage

COPY --from=build-stage /app/build /var/www/html

EXPOSE 80

CMD ["apache2-foreground"]
