FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy proyect
COPY package.json .
RUN npm install

# Copie all the remaining files and directories from the host to the current working directory
COPY . .

# Expose port 3000
EXPOSE 3000

# Start Apache service
CMD ["npm", "start"]