FROM ubuntu:22.04

# Set noninteractive mode for apt-get
ENV DEBIAN_FRONTEND=noninteractive

# Update apt-get
RUN apt-get update

# Install tzdata and set timezone
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
RUN ln -fs /usr/share/zoneinfo/Europe/Barcelona /etc/localtime
RUN dpkg-reconfigure -f noninteractive tzdata

# Install apache2
RUN apt-get install -y apache2

# Install PHP 8.1 and Apache PHP module
RUN apt-get install -y php8.1 libapache2-mod-php8.1

# Enable Apache mod_rewrite
RUN a2enmod rewrite

# Set index.php as the default Apache index file
RUN echo "<Directory /var/www/html>\n\tDirectoryIndex index.php\n</Directory>" >> /etc/apache2/apache2.conf

# Remove the default Apache index.html and copy your index.php into /var/www/html
RUN rm /var/www/html/index.html
COPY ./index.php /var/www/html/index.php

# Open port 80 for apache
EXPOSE 80

# Start Apache service
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
