FROM ubuntu:22.04

# Update apt-get
RUN apt-get update && \
    apt-get install -y --no-install-recommends tzdata && \
    rm -rf /var/lib/apt/lists/*

# Set timezone
RUN ln -fs /usr/share/zoneinfo/Europe/Barcelona /etc/localtime

# Install apache2
RUN apt-get update && \
    apt-get install -y --no-install-recommends apache2 && \
    rm -rf /var/lib/apt/lists/*

# Install PHP 8.1 and Apache PHP module
RUN apt-get update && \
    apt-get install -y --no-install-recommends php8.1 libapache2-mod-php8.1 && \
    rm -rf /var/lib/apt/lists/*

# Enable Apache mod_rewrite
RUN a2enmod rewrite

# Set index.php as the default Apache index file
RUN echo "<Directory /var/www/html>\n\tDirectoryIndex index.php\n</Directory>" >> /etc/apache2/apache2.conf

# Remove the default Apache index.html and copy your index.php into /var/www/html
RUN rm /var/www/html/index.html
COPY ./index.php /var/www/html/index.php

# Open port 80 for apache
EXPOSE 80

# Start Apache service
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
